# Synchronize this repository with its upstream source (Ultimaker/CuraEngine)

name: Synchronize
on:
  # Run on a schedule
  schedule:
    # Run every Saturday at 00:00 UTC
    - cron: '0 0 * * 6'

  # Run when manually triggered
  workflow_dispatch:

jobs:
  diff:
    name: Synchronize with upstream
    runs-on: ubuntu-latest
    steps:
      # Clone downstream (This repository)
      - name: Clone downstream
        uses: actions/checkout@v2
        with:
          ref: sync

      # Add remote upstream
      - name: Add remote upstream
        run: |
          git remote add upstream https://github.com/Ultimaker/CuraEngine.git
          git pull upstream master --allow-unrelated-histories

      # Merge upstream
      - name: Merge upstream
        run: git merge upstream/master

      # Delete workflows
      - name: Delete workflows
        run: rm .github -r

      # Add and commit changes
      - name: Add and commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deleted workflows
          file_pattern: .github

       # Push changes to downstream
      - name: Push to downstream
        run: git push origin sync